version: '3.5'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "4011:5432"
    networks:
      - postgres
    command: >
      bash -c "echo 'CREATE DATABASE $DATABASE_NAME;' > /docker-entrypoint-initdb.d/init.sql && docker-entrypoint.sh postgres"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "4012:80"
    depends_on:
      - postgres
    networks:
      - postgres

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    redis: